#!/usr/bin/env bash
# Push the existing git repository to endpoint location

# Copyright © 2012 Vital Kudzelka.
# Use it for Good not Evil.


ABS_PATH=`dirname "$0"`
source "$ABS_PATH/extra_stuff"

# print usage help
function usage() {
    cat <<HELP
Usage: $(basename "$0") [-h|--help] endpoint
Copy exsisting git repos to predefined destination.

  -h, --help            display this help and exit
HELP
}

# Usage: load <path>
# load source from <path>
function load() {
    if [[ -e "$1" && -r "$1" ]]; then
        prepare && source "$1"
        exit $SUCCESS
    fi
}

# main loop
function loop() {
    while (($#)); do
        case "$1" in
            -h|--help)
                usage;
                exit $SUCCESS;
                ;;
            *)
                to="$ABS_PATH/to/$1"
                load "$to"
                [ "$1" == "--" ] && shift;
                if (($#)); then
                    echo "Usage error: unrecognized option" && usage;
                    exit $E_BAD_PARAMS;
                fi;
        esac
    done
}

loop $@

exit $SUCCESS;
